music/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'music'

urlpatterns = [

    # /music/
    url(r'^$', views.index, name='index'),

    # /music/<album_id>/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    # url(r'^$/'. views.index, name='index')

]

music/models.py
from django.db import models

# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album
from django.http import Http404
from django.http import HttpResponse



def index(request):
    all_albums = Album.objects.all()
    context = {'all_albums': all_albums}
    return render(request, 'music/index.html', context)


def detail(request, album_id):
    # return HttpResponse("<h2>Details for Album id: " + str(album_id) + "</h2>")

    # try:
    #     album = Album.objects.get(pk=album_id)
    # except Album.DoesNotExist:
    #     raise Http404("Album does not exist")
    album = get_object_or_404(Album, pk=album_id) # same as above code
    return render(request, 'music/detail.html', {'album' : album})

music/templates/music/detail.html
<img src = "{{ album.album_logo}}">


<h1>{{  album.album_title  }}</h1>
<h3>{{  album.artist  }}</h3>

<ul>
    {% for song in album.song_set.all %}
        <li>{{ song.song_title }} - {{ song.file_type }}</li>
    {% endfor %}
</ul>

music/templates/music/index.html
{% if all_albums %}
<h3>Here are the albums : </h3>
<ul>
    {% for album in all_albums %}
    <li>
        <a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<h3>You don't have any albums</h3>

{% endif %}